MODEL:
  META_ARCHITECTURE: "ClineDeformModel"
  OUT_CHANNELS: (24,)
  OUT_TASKS: ["features"]
  TASK: ['cline', 'seg']
  PRED_CLASS: 1
  BACKBONE:
    NAME: "build_unetaf_backbone"
DATASETS:
  TRAIN: ("HANS40",)
  TEST: ("HANS40",)
DATALOADER:
  NUM_WORKERS: 7
INPUT:
  CROP_SIZE_TRAIN: (224, 144, 144)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 1e-3
  WEIGHT_DECAY: 1e-3
  WARMUP_ITERS: 250
  WARMUP_FACTOR: 0.3
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  MAX_ITER: 6000
  CHECKPOINT_PERIOD: 1000
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
TEST:
  EVAL_PERIOD: 1000
CUDNN_BENCHMARK: False
